package co.ke.bank.maendeleo.enums;

public enum Industry {

	ADVERTISING, AGRICULTURE, ART, AUTOMOTIVE, BFSI, CONSTRUCTION, GOVERNMENT,
	HEALTHCARE, HOSPITALITY, LAW, LOGISTICS, NGO, REAL_ESTATE, ICT
}
