spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maendeleo_db
    username: mmcs_dbm
    password: <9r0@q7iV3_1O>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          new_generator_mappings: false
server:
  servlet:
    context-path: /api
  port: 8080
logging:
  level:
    root: INFO
---

spring:
  profiles: production
  datasource: 
    url: jdbc:mysql://localhost:3306/maendeleo_db
    username: mmcs_dbm
    password: <9r0@q7iV3_1O>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          new_generator_mappings: false
server:
  servlet:
    context-path: /api
  port: 8080
logging:
  level:
    root: ERROR 